Refactor to reduce code duplication
eisopux/javac-diagnostics-wrapper pull request #129
Opened 2024-10-04 05:00 UTC by XwanXuanX

2024-10-07 18:34 UTC, XwanXuanX commented
Hi to one of the repo's maintainers, I think there is a workflow waiting to be approval before it can be ran. Please approve the workflow so that I can know if my new changes can also be built on the remote. Thank you.

2024-10-30 01:00 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/json/common/Range.java
> +    public Position start;
Can these fields be `final`? Non-final public fields are yuck.

2024-10-30 18:49 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/json/common/Diagnostic.java
> +// Interface for multiple types of Diagnostics (currently: javac, lsp, sarif)
The files in the `common` packages are not specific to json, so they should be moved out of this folder (although the current `javac` and `lsp` output formats are in json).

2024-10-30 19:02 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/json/common/DiagnosticList.java
> +    protected abstract List<Diagnostic> convertOrg(List<javax.tools.Diagnostic<? extends JavaFileObject>> diags);
This is a good point, and I tried exactly the same thing, but failed. The reason is that the json entries in `javac` and `lsp` format are defined differently:

* In `javac`: Each diagnostic forms its own json entry.
* In `lsp`: Diagnostics are grouped by file. In other words, all the diagnostics from the same file forms a json entry.

Therefore, it's hard to define an abstract method for the `Diagnostics` interface, which process each diagnostic **independently** (since some diagnostics need to be grouped by file before processing). So the lowest abstraction level I can identify is a `list of diagnostics`.

If I'm missing something here, please let me know!

2024-10-30 19:11 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/json/common/Range.java
> +    public Position start;
done!

2024-10-30 19:13 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/JavacDiagnosticsWrapper.java
> +import io.github.wmdietl.diagnostics.json.common.Diagnostic;
done!

2024-10-30 19:51 UTC, XwanXuanX commented
The inconsistencise in the author's name has been addressed!

2024-10-30 20:34 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/JavacDiagnosticsWrapper.java
> +import com.google.gson.Gson;
This is a good point!

This file was independent from a particular output encoding so far is because the actual I/O (i.e. writing to stdout) is done in the `Main` function of each specific output format, such as `json/javac/Main.java`. I initially thought that this was redundant since we could extract the I/O part from each `Main` file and put them here, but it created extra dependencies. If the original way is expected and accepted, I can simply revert to that.

The rationale for extracting common I/O part is not only for code duplication. Imagine that we now want to switch from output to stdout to write to file. In this case, we have to go to each `Main` file and modify the output destination. However, with extracted I/O, we now only need to change only one place, which is less prone to error.

2024-10-30 20:36 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/JavacDiagnosticsWrapper.java
> +        List<Diagnostic> result = processDiagnostics(diagnosticCollector.getDiagnostics()).getDiagnostics();
This comment is dependent upon the 1st comment, and can only be resolved after the 1st comment is resolved. Thank you!

2024-11-08 02:08 UTC, wmdietl requested changes
Thanks for all your work on this! Another round of comments that we can discuss tomorrow.

2024-11-08 02:08 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/common/DiagnosticList.java
> +    protected abstract List<Diagnostic> convertOrg(
What does the `Org` stand for? Can you think of a better name?

2024-11-08 02:08 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/common/DiagnosticList.java
> +        return diagnostics;
Is the list mutable? Should this return an immutable view? Or is the caller getting a fresh copy that they can modify? Mention this in the javadoc.

2024-11-08 02:08 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/common/DiagnosticList.java
> +    // Convert from standard javac diagnostic to a specific format
How does one select the "specific format"? The return type uses the generic `Diagnostic`, so where does one see the format?

2024-11-08 02:08 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/common/DiagnosticSeverity.java
> +    public final int value;
`value` is way too generic. Should it be `severity`?
Why is this public? It seems dangerous that this value is directly used by the LSP severity - there has been no mention that the values here need to match LSP severity values.
So instead, keep this private and in LSP have a mapping from these severity values to the LSP severity values.

2024-11-08 02:08 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/json/lsp/LspDiagnostic.java
> +        public final Integer severity;
Why is this an `Integer` and not an `int`?

2024-11-08 02:08 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/json/lsp/LspDiagnostic.java
> +            this.severity = DiagnosticSeverity.convert(diagnostic.getKind()).value;
See earlier comment about converting these correctly - you want a method similar to the one that converts javac severity to the generic severity.
But then... why do you need the middle `DiagnosticSeverity` at all?

2024-11-08 02:08 UTC, wmdietl commented on test.java
> +/**
Adding test cases is great, but not here. Can you find a good place for such tests and automate the test suite?

2024-11-13 22:17 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/JavacDiagnosticsWrapper.java
> +        // Perform certain actions on result, such as write to a file or print to stdout
done!

(as discussed, revert to old version where output to stdout is done in each main function).

2024-11-13 22:18 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/common/DiagnosticList.java
> +    protected abstract List<Diagnostic> convertOrg(
done!

2024-11-13 22:27 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/common/DiagnosticList.java
> +        return diagnostics;
(The file `DiagnosticList.java` is removed entirely when removing unnecessary dependencies.)

I decided to remove this method. Instead, I made the field `diagnostics` public and final. Others can access this field as an immutable view.

2024-11-13 22:31 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/common/DiagnosticList.java
> +    // Convert from standard javac diagnostic to a specific format
This is not an issue anymore.

2024-11-13 22:32 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/json/lsp/LspDiagnostic.java
> +        public final Integer severity;
fixed!

2024-11-13 22:33 UTC, XwanXuanX commented on test.java
> +/**
I will add more testcases, but maybe not in this PR, so I removed it for now.

2024-11-14 00:57 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/common/DiagnosticSeverity.java
> +    public final int value;
I've removed this file since there is no need to have another intermediate representation of severity. Each format could define their own mapping from javac severity to target severity directly. There is no need to translate more than once.

2024-11-14 01:01 UTC, XwanXuanX commented on src/main/java/io/github/wmdietl/diagnostics/json/lsp/LspDiagnostic.java
> +            this.severity = DiagnosticSeverity.convert(diagnostic.getKind()).value;
As discussed in the earlier comments, `Lsp` now defines its own severity mapping to translate javac severity directly. Therefore, there is no need for such a "generic severity", as you pointed out.

2024-11-18 03:10 UTC, wmdietl requested changes
Thanks for all the improvements! I have another round of questions/comments.

2024-11-18 03:10 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/json/javac/JavacDiagnosticList.java
> +    // Convert from a list of standard javac diagnostics to a list of JavacDiagnostic (um, ok...)
What is the `um, ok...` about? Can you clarify?

2024-11-18 03:10 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/json/javac/JavacDiagnosticList.java
> +    public final List<JavacDiagnostic> diagnostics;
The previous code had a private field and a getter method.
Why not keep that?

2024-11-18 03:10 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/json/javac/JavacDiagnosticList.java
> +    // Convert from a list of standard javac diagnostics to a list of JavacDiagnostic (um, ok...)
Is it really worth breaking out this method? This is just called once in the constructor...
The "standard" is also a bit odd naming.

2024-11-18 03:10 UTC, wmdietl commented on src/main/java/io/github/wmdietl/diagnostics/json/javac/JavacDiagnosticList.java
> +    public final List<JavacDiagnostic> diagnostics;
Can you turn your comments into javadoc and document who should modify the lists?

2025-04-29 21:31 UTC, wmdietl commented
Thanks for your work on this! #144 is doing a more extensive refactoring instead.

2025-04-29 21:31 UTC, closed without merging